<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MyWorkItem.Application/MyWorkItem.Application.csproj" />
    <ProjectReference Include="../MyWorkItem.Domain/MyWorkItem.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="SqlKata.Execution" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
</Project>
