<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MyWorkItem.Application\MyWorkItem.Application.csproj" />
    <ProjectReference Include="..\..\src\MyWorkItem.Domain\MyWorkItem.Domain.csproj" />
    <ProjectReference Include="..\..\src\MyWorkItem.Infrastructure\MyWorkItem.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\MyWorkItem.Api\MyWorkItem.Api.csproj" />
  </ItemGroup>

</Project>
